services:
  db:
    image: postgres:16
    container_name: zhat_db
    environment:
      POSTGRES_PASSWORD: zhatroom # 密码设简单点，仅本地开发用
      POSTGRES_DB: zhat_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data # 保证数据不会因为容器重启而消失
